### ISSUE TITLE
Hosted version of styleguide

### ISSUE THREAD

**Issue by sonniesedge** [bitcrowd/bitstyles#163]
If and when Bitstyles is made publicly available, we will need a hosted version of the styleguide that can be linked to from the documentation. 

The styleguide will serve to demo the usefulness of the library and possibly provide a stable reference for visual regression testing.

**Comment by planktonic** [comment]
I’ll close this issue finally, as for a while we’ve had a hosted version of the styleguide available at https://bitcrowd.github.io/bitstyles/ 🙏
