### ISSUE TITLE
Add CI tests

### ISSUE THREAD

**Issue by sonniesedge** [bitcrowd/bitstyles#164]
When this project is open-source and publicly available we should create a [free CI server](https://travis-ci.com/plans) and add linting and other build-time tests. 
- Sass linting
- Javascript linting
- Visual regression tests
- CSS stats

**Comment by planktonic** [comment]
- [] Sass linting
- [ ] Javascript linting
- [ ] Visual regression tests
- [ ] CSS stats

**Comment by planktonic** [comment]
I’ll remove the css stats entry, as that’s not a test it should be run locally and checked in deliberately by devs.

**Comment by planktonic** [comment]
I’ve added `styleguide generation` to the list of items we should be testing on travis (just check the styleguide is correctly generated), as a result of #233.
