### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#249]
In order to make bitstyles as useful as possible within Bitcrowd — for our more traditional projects, not just the frontend-heavy projects — we should add a few components for common requirements:

- tables e.g. admin sections
- menus (list of links or buttons in a row)
  - split link groups, one to the left & one right
- form layout
- sidebar/main page layout

**Comment by RRorg** [comment]
What about an inuit-like approach, where we take the more specialized components and put them into one or more separate add-on repositories?
Of course the goal is not to be another Bootstrap-Drop-In-Solution, but there is no need to reinvent the wheel every time a generic admin panel has to be created.

**Comment by planktonic** [comment]
Yes that could totally work — everything currently in `components/` could be moved out too. Would need to be sure all the base bitstyles variables, functions, & mixins are available.
I found the inuit v3 approach of putting each component into its own repo a bit over the top & counter-productive — probably one repo is enough!

**Comment by planktonic** [comment]
Closing this long-standing issue, as we’ve added the layouts & components mentioned. Further components are being added on a one-per-issue basis :)

**Comment by reneroth** [comment]
talk about an unexpected notification 😬
