### ISSUE TITLE
Better/more examples in the styleguide

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#250]
Right now the styleguide is pretty barebones — it’s more for VRT than as documentation. Add better & more examples of more real-world usages?

**Comment by planktonic** [comment]
Also: make use of `sg-wrapper` to ensure the example markup only contains the markup for the element in question, none of the setup needed around it.

**Comment by RRorg** [comment]
I think the styleguide is doing it's job for the intended target audience.

The bitstyles are so low-level, it's hard to get fancy in the styleguide. What we could do is creating demo designs [like Bootstrap does](http://getbootstrap.com/getting-started/#examples), but even those would be either very bland to look at, or require so much additional code they'd lose their value as examples.

**Comment by planktonic** [comment]
The intent is to improve the examples and introductions/descriptions rather than provide examples of how a complete page may look. I feel much of our docs are currently unclear (especially to readers first encountering the codebase). Ideally a reader will be able to:
- get a clear overview to assess whether the library is suitable for them
- understand the appearance/output/functionality of any given object/mixin/whatever
- quickly understand the examples (currently many have a bunch of boilerplate around the kernel of the example).

To this end I’d suggest:
- Remove any boilerplate markup out of the KSS `markup` field, into the `sg-wrapper`
- Add one-line summaries to encapsulate the purpose of each object in emphasised text at the head of each styleguide page
- Rewrite the descriptive text for clarity & specifics
- Document the variables used in each object.
