### ISSUE TITLE
Styleguide new display context

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#255]
The fixed topbar currently breaks out of its container in the layout section of the styleguide. Using e.g. `transform: translate3d(0,0,0)` would create a new display context within which the topbar could be properly displayed. Any side effects?

**Comment by RRorg** [comment]
we would need to hack together a bit more in the styleguide, the topbar would need a scrollable container with enough content to allow for scrolling... how are other projects solving this issue?

**Comment by planktonic** [comment]
We currently use a few helper classes in `styleguide-extras.scss` (there’s a class in there for setting a minimum height on a container, that could help here). Then the `o-overflow` object could help (https://github.com/bitcrowd/bitstyles/issues/260).

Just to be sure I understood correctly — what’s the exact purpose of making it scalable here, as an example?

**Comment by RRorg** [comment]
It's not strictly needed, but a nice-to-have feature to put the fixed topbar into a scrollable container to truly display its fixed-ness. 🙂

**Comment by planktonic** [comment]
Yup ok, that’s what I thought. Good idea 👍 let’s do it!
