### ISSUE TITLE
link styling

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#257]
Already in safari as default, and recently in chrome canary though set to `none` (and soon in all blink browsers?), we can set the much nicer

```css
text–decoration–skip: ink;
```

on our `.o-link` and base `<a>`. Link underlines will then be nicely intersected by any descenders in the link text.

**Comment by RRorg** [comment]
+1, will probably take a while until this works in any browser (Safari isn't following spec, but merely mimicking the `ink` setting), but no harm in it

**Comment by planktonic** [comment]
It’s in v57(currently canary): https://www.chromestatus.com/feature/4896897575682048. Not an urgent feature but definitely a nice-to-have
