### ISSUE TITLE
Repo image bloat

### ISSUE THREAD

**Issue by RRorg** [bitcrowd/bitstyles#269]
Just so we don't forget about it, we need to separate the reference images from the repo someday™

todo: check how other projects are handling this issue

**Comment by planktonic** [comment]
Could be related to #163 and #164

**Comment by RRorg** [comment]
We could remove the reference images from the repo completely, and instead publish a precompiled version to the #gh-pages branch. Then, on the VRT step, generate fresh reference images from bitcrowd.github.io/bitstyles/ and compare them to the images created from the local project. Reference files could be locally cached too and regenerated on command/every X time units. That should kill both the bloat as well as the inconsistencies between dev machines.

**Comment by planktonic** [comment]
Fixed by #277
