### ISSUE TITLE
Modal scrollbars when external mouse is connected

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#574]
On macOS, when an external mouse is connected the scrollbars disrupt the right & bottom edges of the modal (also check windows, which doesn’t hide scrollbars):

![143836760-552a6844-3f2c-4453-a656-5581acf162f0](https://user-images.githubusercontent.com/2479422/143860489-0f920d75-ad1e-4bb3-8b7c-6e1fa8a6b59e.png)

**Comment by planktonic** [comment]
For context see discussion over on https://github.com/bitcrowd/bitstyles_phoenix/issues/16

**Comment by maltoe** [comment]
it indeed goes away if I follow the instructions from [here](https://stackoverflow.com/a/31835037/10884728) and set "Show scroll bars" to "When scrolling"

![Screenshot 2021-11-29 at 21 15 24](https://user-images.githubusercontent.com/96114/143936422-6f99c2ba-60cc-4fd7-8701-08ef0242e8b6.png)

**Comment by maltoe** [comment]
closed by accident, sorry. The SO answer suggests there is nothing we can do CSS-wise, but TBH I doubt that a bit as I have seen modal dialogs without these borders.

**Comment by planktonic** [comment]
@maltoe yeh we can make it better than it is, I’m pretty sure 👍
