### ISSUE TITLE
select: Remove half the border width from vertical padding

### ISSUE THREAD

**Issue by maltoe** [bitcrowd/bitstyles#576]
Hey @planktonic 

Today I learned something about `<select>` and `<input>` elements in one of our projects (you know which):

The current settings make them both equal in height, but they have different borders on `:focus`:

| input focussed | select focussed |
| - | - |
|![Screenshot 2021-12-02 at 22 17 17](https://user-images.githubusercontent.com/96114/144504753-4f64c310-1cd9-4876-886e-ebfdbfd4101a.png)|![Screenshot 2021-12-02 at 22 17 23](https://user-images.githubusercontent.com/96114/144504783-a3a446c9-f2d5-4d14-8781-1ef121b41e64.png)|

Reason for this is that in our custom settings we have defined

```sass
$padding: size.get('s'),
$border-width: size.get('xxs'),
// among other settings...
```
 
on the text input but not on the `select`:

```sass
$padding-vertical: size.get('s'),
// missing `border-width`
```

If I add that definition, the border is fine, but the `<select>` element becomes taller than its `<input>` friends

![Screenshot 2021-12-02 at 22 17 41](https://user-images.githubusercontent.com/96114/144504975-5ef4c23c-226c-476d-b0cf-bd60a01916af.png)

Reason for that is that for `<input>` you deduct half the border width from the vertical padding:

https://github.com/bitcrowd/bitstyles/blob/d4d94a1c2f5fba31ef73b6e5d525cb92b1190d52/scss/bitstyles/base/input-text/_input-text.scss#L41

... while for `<select>`s you don't

https://github.com/bitcrowd/bitstyles/blob/d4d94a1c2f5fba31ef73b6e5d525cb92b1190d52/scss/bitstyles/base/select/_select.scss#L10

So essentially setting `$vertical-padding` in our project like this:

```sass
$padding-vertical: (size.get('s') - math.div(size.get('xxs'), 2)),
```

Soooo. I'm fine with just setting it in this project, but I wonder if this is a 🐛  in bitstyles and should be fixed? OTOH, it would likely break existing designs, so maybe that is also not an option?

Either way, I thought I'd mention it to you.

👋

**Comment by planktonic** [comment]
@maltoe thanks for the detailed write-up! 💚

Yes I’d call this a bug — projects probably always want the inputs, buttons, & selects to default to the same height as each other. To do that, we need to handle the padding/border in the same way in both (and with the same default values)

Even for projects which have adjusted this manually, I think this is a very minor “breakage” of a couple of pixels, I’d say that’s acceptable

The `$border-width` variable does exist for selects, the same as for inputs. It’s not available on hover tho (same as for inputs) — to avoid the layout jumping around when a border-width changes, the width is set once and only the color can be changed on hover/etc.

**Comment by maltoe** [comment]
> The `$border-width` variable does exist for selects, the same as for inputs. It’s not available on hover tho (same as for inputs) — to avoid the layout jumping around when a border-width changes, the width is set once and only the color can be changed on hover/etc.

Yes, sorry, that was imprecise on my part - the variable exists, but it's apparently even smaller than `xxs`. At least when I set it to `xss`, it became the same (wider) width as the other inputs.
