### ISSUE TITLE
Renaming directional-properties

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#597]
Using `directional-properties.output-properties` is both very long, and somehow misnamed — these generators are more generic than the initial use suggested. Rename to something that makes more sense.

From a discussion [here](https://github.com/bitcrowd/bitstyles/pull/584#discussion_r785003955)

**Comment by klappradla** [comment]
Naming is hard here. In the end it's a utility to generate CSS-class-definitions with a bitstyles-specific name and with the respective properties. So maybe a generic `class-properties.output-properties`?
