### ISSUE TITLE
Size naming

### ISSUE THREAD

**Issue by planktonic** [bitcrowd/bitstyles#666]
A couple of issues with our current naming:

- gap sizes and padding/margin sizes don’t match. This was a decision taken on the basis that a “large” grid gap is `xxxl`, but e.g. a large icon could be `xl` — the name of component’s size is relative to that component instead of to the global sizing scale. With the rise of utility class usage, that’s confusing tho, and means developers need to look up e.g. what size a grid gap is in order to match it with an icon, or padding on another element.
- this is probably a good time to switch to using `l`, `xl`, `2xl`, `3xl` etc. instead of the current `l`, `xl`, `xxl`, `xxxl`

**Comment by ArinzeJeffrey-droid** [comment]
@planktonic Would I have to rebase off this to start working on [this](https://github.com/bitcrowd/bitstyles/pull/665) to start working on this issue?

**Comment by planktonic** [comment]
@ArinzeJeffrey-droid these should be separate tbh — no need to rebase :)
